accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('register/', views.RegisterUserView.as_view(), name='register-user'),
    path('my-account/', views.MyAccountRedirectView.as_view(), name='my-account'),
    path('dashboard/', views.DashboardView.as_view(), name='dashboard'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('activate/<uidb64>/<token>/', views.ActivateView.as_view(), name='activate'),
    path('forgot-password/', views.ForgotPasswordView.as_view(), name='forgot-password'),
    path('reset-password-validate/<uidb64>/<token>/', views.ResetPasswordValidateView.as_view(),
         name='reset-password-validate'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='reset-password'),
    path('subscribe-to-newsletter/', views.SubscribeToNewsletterView.as_view(), name='sub-newsletter'),
    path('newsletter/', views.SendNewsletterView.as_view(), name='newsletter'),
    path('about-us/', views.AboutUsView.as_view(), name='about-us'),
    path('messages-from-users/', views.MessagesFromUsersView.as_view(), name='messages-from-users'),

]

chats/urls.py
from django.urls import path
from django.views.generic import RedirectView

from . import views

urlpatterns = [
    path('', RedirectView.as_view(pattern_name='user-messages', permanent=True)),
    path('my-messages/', views.ChatRoomsView.as_view(), name='user-messages'),
    path('chat-with-support/<str:room_name>/', views.RoomWithSupportRedirectView.as_view(), name='chat-with-support'),
    path('chat-with-user/<str:chat_with>/', views.RoomWithUserRedirectView.as_view(), name='chat-with-user'),
    path('<str:room_name>/', views.ChatRoomWithUserMessages.as_view(), name='chat-room')
]

travelsite/urls.py
"""travelsite URL Configuration"""

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers

from search.views import SearchProductInventory, CategoryList, ProductByCategory, ProductInventoryByWebId
from . import views
from search import views as search_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomeView.as_view(), name='home'),
    path('', include('accounts.urls')),
    path('chat/', include('chats.urls')),
    path('shop/', include('ecommerce.urls')),
    path('forum/', include('forum.urls')),

    # API / Search
    path('api/inventory/category/all/', CategoryList.as_view()),
    path(
        'api/inventory/products/category/<str:query>/',
        ProductByCategory.as_view(),
    ),
    path('api/inventory/<str:query>/', ProductInventoryByWebId.as_view()),
    path('api/search/<str:query>/', SearchProductInventory.as_view(), name='search-api'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db.models import OneToOneField


class UserManager(BaseUserManager):
    """Manager for users."""

    def create_user(self, email, username, password=None, **extra_fields):
        """Create, save and return a new user."""
        if not email:
            raise ValueError('User must have an email address.')
        if not username:
            raise ValueError('User must have an username')

        user = self.model(email=self.normalize_email(email), username=username, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password):
        """Create and return a new superuser."""
        user = self.create_user(email, username, password)
        user.is_staff = True
        user.is_superuser = True
        user.is_active = True
        user.is_superadmin = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser, PermissionsMixin):
    """User in the system."""
    email = models.EmailField(max_length=255, unique=True)
    username = models.CharField(max_length=50, unique=True)
    is_active = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    is_superadmin = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return self.username


class UserProfile(models.Model):
    user = OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True, related_name='user_profile')
    about = models.TextField(max_length=500, blank=True, null=True)
    profile_picture = models.ImageField(upload_to='users/profile_pictures', blank=True, null=True)
    cover_photo = models.ImageField(upload_to='users/cover_photos', blank=True, null=True)
    info_font_color = models.CharField(max_length=15, blank=True)
    address = models.CharField(max_length=250, blank=True, null=True)
    country = models.CharField(max_length=15, blank=True, null=True)
    state = models.CharField(max_length=15, blank=True, null=True)
    city = models.CharField(max_length=15, blank=True, null=True)
    pin_code = models.CharField(max_length=6, blank=True, null=True)
    latitude = models.CharField(max_length=20, blank=True, null=True)
    longitude = models.CharField(max_length=20, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.email


class Subscriber(models.Model):
    email = models.EmailField(unique=True, null=True)
    data_joined = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email


class NewsletterEmail(models.Model):
    """Model for storing already sent newsletter messages."""
    title = models.CharField(max_length=255)
    content = models.TextField()

    def __str__(self):
        return self.title


class MessageToStaff(models.Model):
    """Model for storing messages that visitors/ users
       leave at "about us" page."""
    subject = models.CharField(max_length=100)
    username = models.CharField(max_length=100)
    email = models.EmailField()
    content = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Messages to staff"
        ordering = ['-date']

    def __str__(self):
        return f'{self.username}: {self.subject}'

accounts/views.py
"""
Views for accounts app.
"""
from django.contrib import messages, auth
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.tokens import default_token_generator
from django.contrib.messages.views import SuccessMessageMixin
from django.core.exceptions import PermissionDenied
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse_lazy
from django.utils.http import urlsafe_base64_decode, url_has_allowed_host_and_scheme
from django.views import View
from django.views.generic import FormView, RedirectView, ListView

from accounts.forms import UserForm, UserProfileForm, NewsletterEmailForm, MessageToStaffForm
from accounts.models import User, Subscriber, UserProfile, MessageToStaff
from accounts.utils import detect_user_type, send_verification_email, send_confirmation_email, send_newsletter

EMAIL_SENT_MESSAGE = 'Email sent successfully.'


class RegisterUserView(SuccessMessageMixin, FormView):
    """View for registering a new user."""
    template_name = 'accounts/register_user.html'
    form_class = UserForm
    success_url = reverse_lazy('home')
    success_message = 'Congratulations! Your account has been created.' \
                      'Please check your email to activate it.'

    def form_valid(self, form):
        if self.request.user.is_authenticated:
            messages.warning(self.request, 'You are already logged in!')
            return redirect('my-account')

        username = form.cleaned_data['username']
        email = form.cleaned_data['email']
        password = form.cleaned_data['password']
        user = User.objects.create_user(email=email, username=username, password=password)
        self.send_email(user)
        return super().form_valid(form)

    def form_invalid(self, form):
        if self.request.user.is_authenticated:
            messages.warning(self.request, 'You are already logged in!')
            return redirect('my-account')

    def send_email(self, user):
        """Method for sending verification email."""
        mail_subject = 'Please activate your account'
        email_template = 'accounts/emails/verification_email.html'
        send_verification_email(self.request, user, mail_subject, email_template)


class MyAccountRedirectView(LoginRequiredMixin, RedirectView):
    """view checks is the user an admin or a regular user and
       redirects to appropriate view and page."""

    def get_redirect_url(self, *args, **kwargs):
        return detect_user_type(self.request.user)


class LoginView(View):
    """View for users to log in."""

    def get(self, request):
        if request.user.is_authenticated:
            messages.warning(request, 'You are already logged in.')
            return redirect('my-account')
        return render(request, 'accounts/login.html')

    def post(self, request):
        email = request.POST.get('email')
        password = request.POST.get('password')
        user = auth.authenticate(email=email, password=password)

        if user is not None:
            auth.login(request, user)
            nxt = request.POST.get('next', None)
            if nxt is not None:
                return redirect(nxt)
            return redirect('my-account')
        else:
            messages.error(request, 'Invalid login credentials.')
            return redirect('login')


class LogoutView(RedirectView):
    """View for logging out."""

    def get_redirect_url(self):
        auth.logout(self.request)
        messages.info(self.request, 'You are now logged out.')
        return reverse_lazy('login')


class DashboardView(LoginRequiredMixin, View):
    """View for displaying user dashboard."""
    font_color = ''

    def get(self, request):
        profile = get_object_or_404(UserProfile, user=self.request.user)
        profile_form = UserProfileForm(instance=profile)
        context = {
            'user': request.user,
            'profile_form': profile_form
        }
        return render(request, 'accounts/dashboard.html', context)

    def post(self, request):
        profile = get_object_or_404(UserProfile, user=self.request.user)
        profile_form = UserProfileForm(request.POST, request.FILES, instance=profile)

        if profile_form.is_valid():
            font_color = request.POST.get('font-color')
            profile.info_font_color = font_color
            profile_form.save()
            messages.success(request, 'Settings updated.')
        return redirect('dashboard')


class ActivateView(View):
    """Activate the user by setting the is_active status to True."""

    def get(self, request, uidb64, token):
        try:
            uid = urlsafe_base64_decode(uidb64).decode()
            user = User._default_manager.get(pk=uid)
        except(TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user is not None and default_token_generator.check_token(user, token):
            user.is_active = True
            user.save()
            messages.success(request, 'Congratulation! Your account is activated.')
            return redirect('my-account')
        else:
            messages.error(request, 'Invalid activation link')
            return redirect('my-account')


class ForgotPasswordView(View):
    """View for handling forgotten passwords."""

    def get(self, request):
        return render(request, 'accounts/forgot_password.html')

    def post(self, request):
        email = request.POST['email']

        if User.objects.filter(email=email).exists():
            user = User.objects.get(email__exact=email)

            # send reset password email
            mail_subject = 'Reset Your Password'
            email_template = 'accounts/emails/reset_password_email.html'
            send_verification_email(request, user, mail_subject, email_template)

            messages.success(request, 'Password reset link has been sent to your email address.')
            return redirect('login')
        else:
            messages.error(request, 'Account does not exist')
            return redirect('forgot-password')


class ResetPasswordValidateView(View):
    """View for validating the password reset."""

    def get(self, request, uidb64, token):
        try:
            uid = urlsafe_base64_decode(uidb64).decode()
            user = User._default_manager.get(pk=uid)
        except(TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user is not None and default_token_generator.check_token(user, token):
            request.session['uid'] = uid
            messages.info(request, 'Please reset your password.')
            return redirect('reset-password')
        else:
            messages.error(request, 'This link has expired.')
            return redirect('my-account')


class ResetPasswordView(View):
    """View for resetting passwords."""

    def get(self, request):
        return render(request, 'accounts/reset_password.html')

    def post(self, request):
        password = request.POST.get('password')
        confirm_password = request.POST.get('confirm_password')

        if password == confirm_password:
            pk = request.session.get('uid')
            user = User.objects.get(pk=pk)
            user.set_password(password)
            user.is_active = True
            user.save()
            messages.success(request, 'Password reset successful')
            return redirect('login')
        else:
            messages.error(request, 'Passwords do not match!')
            return redirect('reset-password')


class SubscribeToNewsletterView(View):
    """View for signing up to the newsletter."""

    def post(self, request):
        email = request.POST.get('email')
        Subscriber.objects.create(email=email)
        current_site = request.POST.get('current_site')
        messages.success(request, 'Congratulations! You successfully signed up to our newsletter.')

        # send email to confirm subscription
        mail_subject = f'Hello {email}! '
        email_template = 'accounts/emails/confirm_subscription_email.html'
        send_confirmation_email(email, mail_subject, email_template)
        return redirect(current_site)


class SendNewsletterView(LoginRequiredMixin, UserPassesTestMixin, SuccessMessageMixin, FormView):
    """View for sending newsletter emails to all subscribers."""

    def test_func(self):
        if self.request.user.is_staff:
            return True
        raise PermissionDenied

    form_class = NewsletterEmailForm
    template_name = 'accounts/send_newsletter.html'
    success_url = reverse_lazy('newsletter')
    success_message = EMAIL_SENT_MESSAGE

    def form_valid(self, form):
        title = form.cleaned_data['title']
        content = form.cleaned_data['content']
        email_template = 'accounts/emails/newsletter.html'
        send_newsletter(title, content, email_template)
        form.save()
        return super().form_valid(form)


class AboutUsView(SuccessMessageMixin, FormView):
    """view for "About us" page with option
       to contact the owners of the site
       and start chatting with them."""
    form_class = MessageToStaffForm
    template_name = 'accounts/about_us.html'
    success_url = reverse_lazy('about-us')
    success_message = EMAIL_SENT_MESSAGE

    def get_context_data(self, **kwargs):
        """Getting the context and updating it with slug of ChatRoom.
           It is sent as a string, not an ChatRoom object, because
           the creation of a ChatRoom is not certain, so there would
           be no point in creating an instance of ChatRoom here.
           It will be created when the already logged-in user
           clicks on the "chats-with-support" link."""
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            context['room_name'] = f'{self.request.user.username}__support'
        return context

    def form_valid(self, form):

accounts/templates/accounts/about_us.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    About us
{% endblock %}

{% block content %}
    <div class="page-heading-about" style="background-image: url({% static 'images/about_us_bg.jpg' %});">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h1>About Us</h1>
                </div>
            </div>
        </div>
    </div>

    <div class="about-item">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">

                </div>
                <div class="col-lg-4" style="position: relative; top: 140px;">
                    <div class="right-content">
                        <div class="about-map-image">
                            <img src="{% static 'images/about_us_map.jpg' %}" alt="">
                        </div>
                        <div class="down-content">
                            <h4>Lorem Impsum</h4>
                            <ul>
                                <li>dolor sit amet</li>
                                <li>consectetur adipiscing elit</li>
                            </ul>
                            <span>sed do eiusmod tempor</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="about-upcoming-shows">
        <div class="container">
            <div class="row">
                <div class="col-lg-9">
                    <h2>Something about us</h2>
                    <hr>
                    <h4>This is a fake website that fake-offers things like: </h4>
                    <p class="text-about">
                        <i class="fa fa-compass" aria-hidden="true"></i>Trips to various countries<br>
                        <i class="fa fa-shopping-cart" aria-hidden="true"></i>Shop, where you can buy many things
                        that you will need at your next trip<br>
                        <i class="fa fa-picture-o" aria-hidden="true"></i>Blog about travel<br>
                        <i class="fa fa-comments" aria-hidden="true"></i>Forum for travellers<br>
                        <i class="fa fa-laptop" aria-hidden="true"></i>API - for developers<br>
                    </p><br><br>
                    <h3>It was build as a Django project.</h3>

                </div>
                <div class="col-lg-3">
                    
                </div>
            </div>
        </div>
    </div>

    <div class="also-like">
        <div class="container">
            <div class="row">
                <div class="rent-venue-application ">
                    <div class="col-lg-12">
                        <h2 style="margin-bottom: 40px;">Contact us</h2>
                    </div>
                    <div class="col-lg-12">
                        <h3>Send us a message</h3>
                        <a class="chat-with-us" href="
                        {% if request.user.is_authenticated %}
                            {% url 'chat-with-support' room_name %}
                        {% else %}
                            {% url 'login' %}
                        {% endif %}
                            ">
                            <h3><i class="fa fa-comments" aria-hidden="true"></i> or chat with us</h3>
                        </a>
                    </div>
                    <div class="container ">
                        <div class="row">
                            <div class="col-lg-10">
                                <div class="like-item">
                                    <div class="contact-form">
                                        <form id="contact" action="{% url "about-us" %}" method="post">
                                            {% csrf_token %}
                                            <div class="row">
                                                <div class="col-md-12 col-sm-12">
                                                    <fieldset>
                                                        <label>Subject:</label>
                                                        {{ form.subject }}
                                                    </fieldset>
                                                    {% if form.subject.errors %}
                                                        {% for error in form.subject.errors %}
                                                            <label style="color: red;">{{ error }}</label>
                                                        {% endfor %}
                                                    {% endif %}
                                                </div>
                                                <div class="col-md-12 col-sm-12">
                                                    <fieldset>
                                                        <label>Your name:</label>
                                                        {{ form.username }}
                                                    </fieldset>
                                                    {% if form.username.errors %}
                                                        {% for error in form.username.errors %}
                                                            <label style="color: red;">{{ error }}</label>
                                                        {% endfor %}
                                                    {% endif %}
                                                </div>

                                                <div class="col-md-12 col-sm-12">
                                                    <fieldset>
                                                        <label>Your email address:</label>
                                                        {{ form.email }}
                                                    </fieldset>
                                                    {% if form.email.errors %}
                                                        {% for error in form.email.errors %}
                                                            <label style="color: red;">{{ error }}</label>
                                                        {% endfor %}
                                                    {% endif %}
                                                </div>
                                                <div class="col-md-12 col-sm-12">
                                                    <fieldset>
                                                        <label>Message:</label>
                                                        {{ form.content }}
                                                    </fieldset>
                                                    {% if form.content.errors %}
                                                        {% for error in form.content.errors %}
                                                            <label style="color: red;">{{ error }}</label>
                                                        {% endfor %}
                                                    {% endif %}
                                                </div>

                                                <div class="col-lg-12">
                                                    <fieldset>
                                                        <button type="submit" id="form-submit" class="main-dark-button">
                                                            Send
                                                        </button>
                                                    </fieldset>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

accounts/templates/accounts/dashboard.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Dashboard
{% endblock %}

{% block content %}
    <!-- ***** Dashboard content ***** -->
    <div class="page-heading-rent-venue" style="background-image: url(
            {% if user.user_profile.cover_photo %}
                {{ user.user_profile.cover_photo.url }}
            {% else %}
                {% static 'images/default_cover_photo.jpg' %}
            {% endif %}
            );">
        <div class=" container">
            <div class="row profile-info">
                <img src="
                {% if user.user_profile.profile_picture %}
                    {{ user.user_profile.profile_picture.url }}
                {% else %}
                    {% static 'images/default_profile_picture.png' %}
                {% endif %}" alt="Profile picture">
                <div class="col-lg-12">
                    <h2 style="color: {{ user.user_profile.info_font_color }};">{{ user.username }}</h2>
                    <span style="color: {{ user.user_profile.info_font_color }};">{% if user.user_profile.about %}
                        {{ user.user_profile.about }}
                    {% endif %}
                    </span>
                </div>
            </div>
        </div>
    </div>


    <div class="rent-venue-application">
        <div class="container">
            <div class="row">
                <div class="col-lg-9">
                    <div class="heading-text">
                        <h4>Edit your account details</h4>
                    </div>
                    <div class="contact-form">
                        <form id="contact" action="{% url 'dashboard' %}" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="row">

                                <div class="col-md-12 col-sm-12">
                                    <fieldset>
                                        <label>Tell us something about yourself:</label>
                                        {{ profile_form.about }}
                                    </fieldset>
                                </div>
                                <div class="col-md-10 col-sm-12">
                                    <fieldset>
                                        <label>Your Address:</label>
                                        {{ profile_form.address }}
                                    </fieldset>
                                </div>
                                <div class="col-md-2 col-sm-12">
                                    <fieldset>
                                        <label style="text-align: center;" for="colorpicker">Choose color of the info
                                            text above:</label>
                                        <input name='font-color' type="color" id="colorpicker"
                                               value="{{ user.user_profile.info_font_color }}">
                                    </fieldset>
                                </div>
                                <div class="col-md-5 col-sm-12 mb-3">
                                    <fieldset>
                                        <label for="id_profile_picture">Profile picture:</label>
                                        {{ profile_form.profile_picture }}
                                    </fieldset>
                                </div>

                                <div class="col-md-6 col-sm-12">
                                    <fieldset>
                                        <label for="id_cover_photo">Cover photo:</label>
                                        {{ profile_form.cover_photo }}
                                    </fieldset>
                                </div>

                                <div class="col-md-6 col-sm-12">
                                    <fieldset>
                                        <label>Country:</label>
                                        {{ profile_form.country }}
                                    </fieldset>
                                </div>
                                <div class="col-md-6 col-sm-12">
                                    <fieldset>
                                        <label>State:</label>
                                        {{ profile_form.state }}
                                    </fieldset>
                                </div>
                                <div class="col-md-6 col-sm-12">
                                    <fieldset>
                                        <label>City:</label>
                                        {{ profile_form.city }}
                                    </fieldset>
                                </div>
                                <div class="col-md-6 col-sm-12">
                                    <fieldset>
                                        <label>Pin code:</label>
                                        {{ profile_form.pin_code }}
                                    </fieldset>
                                </div>
                                <div class="col-md-6 col-sm-12">
                                    <fieldset>
                                        <label>Latitude:</label>
                                        {{ profile_form.latitude }}
                                    </fieldset>
                                </div>
                                <div class="col-md-6 col-sm-12">
                                    <fieldset>
                                        <label>Longitude:</label>
                                        {{ profile_form.longitude }}
                                    </fieldset>
                                </div>

                                <div class="col-lg-12">
                                    <fieldset>
                                        <button type="submit" id="form-submit" class="main-dark-button">Submit</button>
                                    </fieldset>
                                </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br><br>
{% endblock %}